### ISSUE TITLE
add support for wikidata identifiers

### ISSUE THREAD

**Issue by abubelinha** [inveniosoftware/idutils#102]
## Is your feature request related to a problem? Please describe.
Zenodo records' metadata include the option to add creators' identifiers:
- for **people**: [ORCID](https://en.wikipedia.org/wiki/ORCID), [ISNI](https://en.wikipedia.org/wiki/International_Standard_Name_Identifier) or [GND](https://en.wikipedia.org/wiki/Integrated_Authority_File) identifiers are supported, but none of them is useful for dead non well known people (i.e. a person who collaborated in a field trip to collect some museum specimens years ago and passed away; or maybe also alive people who collected specimens but do not have an ORCID, ISNI or GND because they are not actively publishing or working in any research institution ... so museum's curators have no way to locate an ID to identify them)
- for **organizations**: [ROR](https://en.wikipedia.org/wiki/Research_Organization_Registry), [ISNI](https://en.wikipedia.org/wiki/International_Standard_Name_Identifier) or [GND](https://en.wikipedia.org/wiki/Integrated_Authority_File) identifieres are supported, but none of them seems either useful for identifying some particular groups of people (for example, a scientific expedition made centuries ago, a research lab, a NGO project, ...)

## Describe the solution you'd like
Wikidata identifiers are valid for anything, so they are very useful for filling those gaps
- identifiers for dead people not having an orcid or similar alternative identifiers [Q21392555](https://www.wikidata.org/wiki/Q21392555)
- identifiers for groups of people not having or not suitable to get an "organization id", like a scientific expedition: [Q1227138](https://www.wikidata.org/wiki/Q1227138)

A very common use context is an old museum item which can be authored by any of the above (collected by a known dead person, or by a group of several people who collaborated to collect it). 
The item needs to be uploaded to Zenodo in order to get a DOI which makes it suitable to be cited in a publication. 

So the item authorship should be provided too, and we need identifiers for it.  Wikidata identifiers are just perfect for this.

## Describe alternatives you've considered
I asked to Zenodo by email [Ticket#33303] and their support staff kindly emailed me back with this answer:
> "we definitely see the use case as a valid one. We'll need to add support for Wikidata identifiers in https://github.com/inveniosoftware/idutils first to achieve it"

## Additional context
- I had previously opened this related Zenodo issue: https://github.com/zenodo/zenodo/issues/2508
- Also discussed [here](https://github.com/bionomia/bionomia/issues/222#issuecomment-1833977437). 
  See how Wikidata ids are being created and used in Bionomia project: https://bionomia.net/help
  Example of a explorer's wikidata-based id in Bionomia: [Q405702](https://bionomia.net/Q405702/)

**Comment by wgresshoff** [comment]
Done by https://github.com/inveniosoftware/idutils/pull/131

**Comment by abubelinha** [comment]
Thanks @wgresshoff 
Do you have any idea of how long could it take this feature to be available in Zenodo portal?
I tried again to add a wikidata identifier (to a Zenodo upload author), but I still get a message of "**No valid scheme recognized for identifie**r."

**Comment by wgresshoff** [comment]
@slint I'll do that. Hope I'll find the release notes.
